### ISSUE TITLE
flipper2text errors out on MAC with Python 3.9.6

### ISSUE THREAD

**Issue by ruibinghao** [astrospark/flippertools#1]
Hi, I was testing out your code on my MacBookPro OSX (13.2.1) with Python 3.9.6. Unfortunately it was erroring out right away. I am not sure what I may have missed to get the code up and running. 

RHao000@RESML-1725925 flippertools-main % python3 --version
Python 3.9.6

RHao000@RESML-1725925 flippertools-main % pip3 list |grep virtual
virtualenv             20.24.3

RHao000@RESML-1725925 flippertools-main % ./flipper2text Project7.llsp
Collecting tzlocal~=4.2
  Downloading tzlocal-4.3.1-py3-none-any.whl (20 kB)
Collecting hexdump~=3.3
  Downloading hexdump-3.3.zip (12 kB)
Collecting pytz-deprecation-shim
  Downloading pytz_deprecation_shim-0.1.0.post0-py2.py3-none-any.whl (15 kB)
Collecting tzdata
  Downloading tzdata-2023.3-py2.py3-none-any.whl (341 kB)
     |████████████████████████████████| 341 kB 3.0 MB/s
Using legacy 'setup.py install' for hexdump, since package 'wheel' is not installed.
Installing collected packages: tzdata, pytz-deprecation-shim, tzlocal, hexdump
    Running setup.py install for hexdump ... done
Successfully installed hexdump-3.3 pytz-deprecation-shim-0.1.0.post0 tzdata-2023.3 tzlocal-4.3.1
WARNING: You are using pip version 21.2.4; however, version 23.2.1 is available.
You should consider upgrading via the '/private/tmp/flippertools-main/venv/bin/python3 -m pip install --upgrade pip' command.
Traceback (most recent call last):
  File "/private/tmp/flippertools-main/flipper2text.py", line 8, in <module>
    from flipperfile import FlipperFile
  File "/private/tmp/flippertools-main/flipperfile.py", line 8, in <module>
    class FlipperFile:
  File "/private/tmp/flippertools-main/flipperfile.py", line 9, in FlipperFile
    def __init__(self, file: str | PathLike[str] | IO[bytes]):
TypeError: unsupported operand type(s) for |: 'type' and 'types.GenericAlias'

**Comment by ruibinghao** [comment]
Please ignore this reported issue. I upgraded my Python to 3.11.5 and I was able to execute the flipper2text command successfully.

**Comment by rmcardle** [comment]
Thanks for the report. I have confirmed that Python 3.10 or higher is required. I've added that information to the README.
